// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_fetch_function_content
CharacterVector cpp_fetch_function_content(const std::string& function_name);
RcppExport SEXP _autograder_cpp_fetch_function_content(SEXP function_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type function_name(function_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fetch_function_content(function_name));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fetch_problems_list
CharacterVector cpp_fetch_problems_list();
RcppExport SEXP _autograder_cpp_fetch_problems_list() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_fetch_problems_list());
    return rcpp_result_gen;
END_RCPP
}
// cpp_compare_identical
LogicalVector cpp_compare_identical(SEXP obj1, SEXP obj2);
RcppExport SEXP _autograder_cpp_compare_identical(SEXP obj1SEXP, SEXP obj2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj1(obj1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type obj2(obj2SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_compare_identical(obj1, obj2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_autograder_cpp_fetch_function_content", (DL_FUNC) &_autograder_cpp_fetch_function_content, 1},
    {"_autograder_cpp_fetch_problems_list", (DL_FUNC) &_autograder_cpp_fetch_problems_list, 0},
    {"_autograder_cpp_compare_identical", (DL_FUNC) &_autograder_cpp_compare_identical, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_autograder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
