name: Bug report

description: Report a bug or unexpected behavior in R-Function-checker
title: "[Bug] Short description"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      options:
        - R package (autograder)
        - C++ backend
        - Tools (instructor utilities)
        - Documentation

  - type: input
    id: version
    attributes:
      label: Package / commit version
      description: R package version, Git SHA, or branch name.

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: R version, OS, and any other relevant details.
      placeholder: |
        - R version: 
        - OS: 
        - How installed (source, devtools, etc.):

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context, logs, or screenshots here.
