name: Feature request

description: Suggest a new feature or improvement for R-Function-checker
title: "[Feature] Short description"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve R-Function-checker! Please describe the feature you have in mind.

  - type: textarea
    id: summary
    attributes:
      label: Feature summary
      description: A clear and concise description of the feature.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful? Who does it help (students, instructors, maintainers)?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How would you like this feature to work? Include examples if helpful.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or workarounds you have tried.

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context, diagrams, or references here.
