name: Question

description: Ask a question about using or extending R-Function-checker
title: "[Question] Short description"
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Use this template if you have a question about how to use the autograder, how to set up problems, or how to extend the system.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Clearly describe your question.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any context that might help answer your question (course setup, environment, etc.).

  - type: textarea
    id: attempts
    attributes:
      label: What you have tried
      description: List any steps, docs, or examples you already checked.
