# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get GitHub URL for instructor function (hidden in compiled binary)
#' @keywords internal
.cpp_get_function_url <- function(function_name) {
    .Call(`_autograder_cpp_get_function_url`, function_name)
}

#' Compare two outputs for identical match (hidden in compiled binary)
#'
#' @param obj1 First object
#' @param obj2 Second object
#' @return Logical vector. TRUE if identical, FALSE otherwise
#' @keywords internal
.cpp_compare_identical <- function(obj1, obj2) {
    .Call(`_autograder_cpp_compare_identical`, obj1, obj2)
}

