# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast comparison of R objects using C++
#' @keywords internal
.cpp_compare_fast <- function(obj1, obj2, tolerance = 1e-10) {
    .Call(`_autograder_cpp_compare_fast`, obj1, obj2, tolerance)
}

#' Securely fetch function content with improved error handling
#' @keywords internal
.cpp_fetch_function_content <- function(function_name) {
    .Call(`_autograder_cpp_fetch_function_content`, function_name)
}

#' Securely fetch problems list
#' @keywords internal
.cpp_fetch_problems_list <- function() {
    .Call(`_autograder_cpp_fetch_problems_list`)
}

#' Legacy comparison function (kept for compatibility)
#' @keywords internal
.cpp_compare_identical <- function(obj1, obj2) {
    .Call(`_autograder_cpp_compare_identical`, obj1, obj2)
}

